name: react ci pipeline
on: 
  push:
    branches:
        - main
  workflow_dispatch:
jobs:
   build:
    runs-on: ubuntu-latest
    steps:
         - name: Checkout Repository
           uses: actions/checkout@v5

         - name: Setup Node.js
           uses: actions/setup-node@v5
           with:
              node-version: 22

         - name: Install Dependencies
           run: npm install

         - name: Run Unit Tests
           run: npm test 

         - name: Build React App
           run: npm run build

         - name: Upload Build Artifact
           uses: actions/upload-artifact@v4
           with:
             name: react-build
             path: dist/   